### ISSUE TITLE
loading last page + Home Screen

### ISSUE THREAD

**Issue by TheBigBlase** [Virtual5oul/virtual5oul.github.io#1]
Home page : Don't count with px, pls use % of picture; Ex : 50% and not 18px 
Loading Last Page : White screen, nothing else.

**Comment by Virtual5oul** [comment]
You reported 2 different issues in the same post, don't do that next time

**Comment by Virtual5oul** [comment]
websiteVersion is already positionning with percentages.
Use latest versions of Firefox or Chrome to avoid white screens.
